name: Docker Image CI

on:
  workflow_call:
    inputs:
      tag_prefix:
        required: true
        type: string
    secrets:
      username:
        required: true
      password:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # See https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      # See https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # See https://github.com/docker/login-action
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}

      # See https://github.com/docker/build-push-action/blob/master/docs/advanced/multi-platform.md
      - name: Build and push Apache httpd variant
        uses: docker/build-push-action@v2
        with:
          file: apache.dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
          push: true
          tags: |
            ${{ github.repository }}:${{ inputs.tag_prefix }}-apache
            ${{ github.repository }}:${{ inputs.tag_prefix }}
            ${{ github.repository }}:apache
            ${{ github.repository }}:latest

      - name: Build and push nginx variant
        uses: docker/build-push-action@v2
        with:
          file: apache.dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
          push: true
          tags: |
            ${{ github.repository }}:${{ inputs.tag_prefix }}-nginx
            ${{ github.repository }}:nginx
