# See https://github.com/docker/build-push-action/blob/master/docs/advanced/multi-platform.md

name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # See https://github.com/docker/setup-qemu-action
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    # See https://github.com/docker/setup-buildx-action
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # See https://github.com/docker/login-action
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push (amd64)
      uses: docker/build-push-action@v2
      with:
        file: amd64.dockerfile
        push: true
        tags: ckulka/docker-multi-arch-example-gh:amd64

    - name: Build and push (arm32v5)
      uses: docker/build-push-action@v2
      with:
        file: amd64.dockerfile
        push: true
        tags: ckulka/docker-multi-arch-example-gh:arm32v5
