# See https://github.com/docker/build-push-action/blob/master/docs/advanced/multi-platform.md

name: Docker Image CI

on:
  workflow_call:
    inputs:
      variant:
        required: true
        type: string
      variant_prefix:
        required: true
        type: string
    secrets:
      username:
        required: true
      password:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ github.repository }}

      # See https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      # See https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # See https://github.com/docker/login-action
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}

      # Platforms argument not needed, because we build on amd64
      - name: Build and push ${{ inputs.variant_prefix }}amd64
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ github.repository }}:${{ inputs.variant_prefix }}amd64

      # Edge case: platform not supported by QEMU and Alpine base images don't
      # exist. Workaround is to use a separate Dockerfile and correct the
      # annotations later with docker manifest command.
      - name: Build and push ${{ inputs.variant_prefix }}arm32v5
        uses: docker/build-push-action@v2
        with:
          file: arm32v5.dockerfile
          push: true
          tags: ${{ github.repository }}:${{ inputs.variant_prefix }}arm32v5

      - name: Build and push ${{ inputs.variant_prefix }}arm32v7
        uses: docker/build-push-action@v2
        with:
          platforms: linux/arm/v7
          push: true
          tags: ${{ github.repository }}:${{ inputs.variant_prefix }}arm32v7

      - name: Build and push ${{ inputs.variant_prefix }}arm64v8
        uses: docker/build-push-action@v2
        with:
          platforms: linux/arm64/v8
          push: true
          tags: ${{ github.repository }}:${{ inputs.variant_prefix }}arm64v8

      # Build the manifest, fix the annotations for our arm32v5 edge case and
      # upload the manifest to the Docker registry.
      - name: Publish multi-arch manifest ${{ inputs.variant }}
        run: |
          docker manifest create ${{ github.repository }}:${{ inputs.variant }} \
            ${{ github.repository }}:${{ inputs.variant_prefix }}amd64    \
            ${{ github.repository }}:${{ inputs.variant_prefix }}arm32v5  \
            ${{ github.repository }}:${{ inputs.variant_prefix }}arm32v7  \
            ${{ github.repository }}:${{ inputs.variant_prefix }}arm64v8
          docker manifest annotate --os linux --arch arm --variant v5 ${{ github.repository }}:${{ inputs.variant }} ${{ github.repository }}:${{ inputs.variant_prefix }}arm32v5
          docker manifest push ${{ github.repository }}:${{ inputs.variant }}
        env:
          # This flag won't be needed in later versions of Docker. It has been
          # deprecated, experimental features will be enabled by default.
          DOCKER_CLI_EXPERIMENTAL: enabled
