name: master

on:
  push:
    branches:
      - master

jobs:
  experimental:
    uses: ckulka/docker-multi-arch-example-gh/.github/workflows/docker-image.yml@master
    with:
      variant: experimental
      variant_prefix: experimental-
    secrets:
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}
