name: release

on:
  release:
    types:
      - published

jobs:
  latest:
    uses: ckulka/docker-multi-arch-example-gh/.github/workflows/docker-image.yml@master
    with:
      variant: latest
      variant_prefix: ""
    secrets:
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}

  release:
    uses: ckulka/docker-multi-arch-example-gh/.github/workflows/docker-image.yml@master
    with:
      variant: ${{ github.ref_name }}
      variant_prefix: ${{ github.ref_name }}-
    secrets:
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}
